### ISSUE TITLE
Criar estrutura HTML para os campos

### ISSUE THREAD

**Issue by CarlaPonciano** [lucasbald/feedback-extension#4]
- [x] Criar protótipo da estrutura
- [x] Criar mesma estrutura de campos da planilha no HTML para envio dos dados

Utilizar extensão dark reader como modelo:
![dark reader](https://user-images.githubusercontent.com/49000683/150803389-435cda49-af51-4646-82d5-59d96c5057de.png)

Templates Figma: https://www.figma.com/templates/

**Comment by lucasbald** [comment]
Prototipo da estrutura:
![image](https://user-images.githubusercontent.com/4924920/153881784-b20d4940-0192-4990-990e-57475c90a611.png)
